version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - db.env
    volumes:
      - backend_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  backend_data:
